# Generated by Django 4.2.16 on 2024-09-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_personal_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal_info',
        ),
    ]
