# Generated by Django 4.2.16 on 2024-09-25 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0003_delete_personal_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('BMI', models.FloatField(default=0)),
                ('phone', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('trainer', 'Trainer'), ('manager', 'Manager')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
