# Generated by Django 4.2.16 on 2024-09-25 15:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0005_category_schedules_alter_membership_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fitness_class',
            new_name='FitnessClass',
        ),
        migrations.RenameModel(
            old_name='Personal_info',
            new_name='PersonalInfo',
        ),
    ]
