# Generated by Django 4.2.16 on 2024-09-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_rename_fitness_class_fitnessclass_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='BMI',
            new_name='bmi',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='BMI',
            new_name='bmi',
        ),
    ]
