# Generated by Django 5.1.1 on 2024-09-26 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_remove_personalinfo_role_fitnessclass_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessclass',
            name='categories',
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='categories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fitness.category'),
        ),
    ]
