# Generated by Django 5.1.1 on 2024-09-26 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_remove_fitnessclass_schedule_schedules_fitnessclass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermembership',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='fitnessclass',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='user',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='schedules',
            name='fitnessclass',
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='schedule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fitness.schedules'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.category'),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
