# Generated by Django 5.1.1 on 2024-09-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_rename_user_customermembership_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessclass',
            name='schedule',
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='end_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='start_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default=None, max_length=10),
        ),
        migrations.DeleteModel(
            name='Schedules',
        ),
    ]
