# Generated by Django 4.2.16 on 2024-10-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_alter_fitnessclass_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='profile_images/'),
        ),
    ]
